futurakart_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


futurakart_velocity_controller:
  type: "ackermann_controller/AckermannController"
  base_length: 0.33
  child_frame_id: base_footprint
  cmd_timeout: 0.25
#  drive_joint_names: ['front_left_wheel_joint', 'front_right_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint']
  drive_joint_names: 'rear_right_wheel_joint'
  frame_id: odom
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 3.0]
  publish_rate: 50
  steering_joint_names: ['front_left_steering_joint', 'front_right_steering_joint']
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 3.0]
  wheel_diam: 0.105


#futurakart_velocity_controller:
#  type: "diff_drive_controller/DiffDriveController"
#  left_wheel: ['front_left_wheel', 'rear_left_wheel']
#  right_wheel: ['front_right_wheel', 'rear_right_wheel']
#  publish_rate: 50
#  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
#  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
#  cmd_vel_timeout: 0.25
#
#  k_l: 0.1
#  k_r: 0.1
#
#  # Odometry fused with IMU is published by robot_localization, so
#  # no need to publish a TF based on encoders alone.
#  enable_odom_tf: false
#
#  # Wheel separation and radius multipliers
#  wheel_separation_multiplier: 1.5 # default: 1.0
#  wheel_radius_multiplier    : 1.0 # default: 1.0
#
#  # Velocity and acceleration limits
#  # Whenever a min_* is unspecified, default to -max_*
#  linear:
#    x:
#      has_velocity_limits    : true
#      max_velocity           : 2.0   # m/s
#      has_acceleration_limits: true
#      max_acceleration       : 20.0   # m/s^2
#  angular:
#    z:
#      has_velocity_limits    : true
#      max_velocity           : 4.0   # rad/s
#      has_acceleration_limits: true
#      max_acceleration       : 25.0   # rad/s^2


