futurakart_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


futurakart_velocity_controller:
  type: "ackermann_controller/AckermannController"
  base_length: 1.0 # exactly one meter
  child_frame_id: base_footprint
  cmd_timeout: 0.25
  drive_joint_names: ['rear_left_wheel', 'rear_right_wheel', 'front_left_wheel', 'front_right_wheel']
  frame_id: /ackermann_controller/odom # In pusblished odometry message header.frame_id
  odom_topic: /ackermann_controller/odom
  ackermann_cmd_topic: /ackermann_cmd
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 3.0]
  publish_rate: 50
  #steering_joint_names: ['front_left_wheel', 'front_right_wheel']
  steering_joint_names: ['front_left_steering_arm', 'front_right_steering_arm']
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 3.0]
  wheel_diameter: 0.250 # 2 * 0.125

  # Propulsion speed and direction position limits:
  drive_max_velocity: 0.6 # m/s
  drive_min_velocity: -0.6 # m/s
  steering_min_angle: -0.45 # rad
  steering_max_angle: 0.45 # rad


