futurakart_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


futurakart_velocity_controller:
  type: "ackermann_controller/AckermannController"
  base_length: 0.33
  child_frame_id: base_footprint
  cmd_timeout: 0.25
  drive_joint_names: ['rear_left_wheel', 'rear_right_wheel']
  frame_id: odom
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 3.0]
  publish_rate: 50
  steering_joint_names: ['front_left_wheel', 'front_right_wheel']
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 3.0]
  wheel_diam: 0.105

