#Configuation for robot odometry EKF
# http://docs.ros.org/kinetic/api/robot_localization/html/

# The real-valued frequency, in Hz, at which the filter produces a state estimate 
frequency: 50

# 
two_d_mode: true

odom0: /ackermann_controller/odom
# (X,Y,Z, roll,pitch,yaw, VX,VY,VZ, Vroll,Vpitch,Vyaw, AX,AY,AZ)
odom0_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: true


odom1: /odom
# (X,Y,Z, roll,pitch,yaw, VX,VY,VZ, Vroll,Vpitch,Vyaw, AX,AY,AZ)
odom1_config: [true, true, false,
               false, false, true,
               true, true, false,
               false, false, true,
               false, false, false]
odom1_differential: true


publish_tf: true
odom_frame: odom
base_link_frame: base_link
world_frame: odom
